name: GLaDOS Auto Checkin

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # 允许网页手动触发
  schedule:
    # 采用高频补签策略，对抗 GitHub Actions 的随机丢包和延迟
    - cron: '0 2 * * *'   # 第一次：北京时间 上午 10:00
    - cron: '0 10 * * *'  # 第二次：北京时间 傍晚 18:00
    - cron: '0 18 * * *'  # 第三次：北京时间 凌晨 02:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run checkin script
      env:
        COOKIE: ${{ secrets.GLADOS_COOKIES }}
      run: |
        sed -i "s|MY_COOKIE = \".*\"|MY_COOKIE = \"$COOKIE\"|g" glados.py
        python glados.py
